openapi: 3.1.0
info:
  title: Kubit Banking API
  description: |
    La **Kubit Banking API** es una solución completa para la integración con el sistema de banca en línea de Kubit. 
    Esta API permite a los desarrolladores crear aplicaciones que interactúen con diversas funcionalidades bancarias, 
    incluyendo la autenticación de usuarios, gestión de cuentas, transferencia de fondos, manejo de tarjetas de crédito y débito, 
    así como la generación de reportes detallados de movimientos y saldos.

    ### Principales Funcionalidades:
    
    - **Autenticación y Sesiones:** Permite a los usuarios iniciar sesión de manera segura y gestionar sus sesiones. 
    - **Transferencias:** Facilita la transferencia de dinero entre cuentas dentro del mismo banco y hacia otras instituciones financieras.
    - **Gestión de Tarjetas:** Permite la gestión de tarjetas de crédito y débito, incluyendo la activación, desactivación, y consulta de detalles.
    - **Consultas de Saldos y Movimientos:** Proporciona acceso a la información detallada de saldos y movimientos de cuentas, permitiendo generar reportes personalizados.
    - **Pagos y Servicios:** Integra funcionalidades para la realización de pagos de servicios y otras transacciones monetarias.

    ### Seguridad:
    
    Todas las interacciones con la API requieren autenticación a través de tokens JWT. 
    Además, se recomienda el uso de HTTPS para todas las comunicaciones con la API para garantizar la seguridad y privacidad de los datos.

    ### Público Objetivo:
    
    Esta API está diseñada para desarrolladores que buscan integrar capacidades bancarias en sus aplicaciones, 
    desde aplicaciones móviles hasta soluciones web para la gestión financiera.
  version: 0.0.1
tags: 
  - name: Authentication
    description: 'Operaciones relacionadas con la autenticación de usuarios y manejo de sesiones.'
  - name: Transfers
    description: 'Operaciones relacionadas con el envío y recepción de dinero entre cuentas.'
  - name: Cards
    description: 'Operaciones relacionadas con la gestión de tarjetas de crédito y débito.'
  - name: Reports
    description: 'Operaciones relacionadas con la generación de reportes de movimientos y saldos de cuentas.'
  - name: Payments
    description: 'Operaciones relacionadas con la realización de pagos de servicios y otras transacciones monetarias.'
paths:
  /api/v1/auth/login:
    post:
      summary: Autenticación / Login
      deprecated: false
      description: |
        Permite a los usuarios autenticarse en la plataforma Kubit. 
        Se requiere un nombre de usuario y una contraseña válidos para obtener un token de sesión. 
        Este token se utiliza para autenticar futuras solicitudes a la API.
      operationId: login
      tags: 
        - Authentication
      parameters:
        - name: Kubit-Api-Key
          in: header
          description: 'Clave API única para autenticar la solicitud. Proporcione esta clave en el encabezado de la solicitud.'
          required: false
          example: KU_YOUR_KEY
          schema:
            type: string
      requestBody:
        description: 'Credenciales requeridas para iniciar sesión en el sistema.'
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 'Nombre de usuario registrado en el sistema.'
                  example: 'user123'
                password:
                  type: string
                  format: password
                  description: 'Contraseña correspondiente al nombre de usuario.'
                  example: '********'
              required:
                - password
                - username
      responses:
        '200':
          description: 'Inicio de sesión exitoso. Devuelve un token de autenticación que se utilizará para las siguientes solicitudes.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                    description: 'Estado de la solicitud. En este caso, "ok" indica que la autenticación fue exitosa.'
                    example: "ok"
                  Code:
                    type: integer
                    description: 'Código de estado HTTP correspondiente a la respuesta. 200 indica éxito.'
                    example: 200
                  Data:
                    type: object
                    description: 'Objeto que contiene los datos resultantes de la autenticación exitosa, como el token de sesión.'
                    properties:
                      token:
                        type: string
                        description: 'Token JWT utilizado para autenticar futuras solicitudes.'
                        example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        '401':
          description: 'Autenticación fallida. Esto ocurre cuando las credenciales proporcionadas son incorrectas.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 'Mensaje de error indicando la naturaleza del problema.'
                    example: 'Unauthorized'
        '500':
          description: 'Error interno del servidor. Ocurre cuando hay un problema en el servidor durante el procesamiento de la solicitud.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 'Mensaje de error indicando un fallo interno en el servidor.'
                    example: 'Internal Server Error'
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
